- name: Create a Controller ELB security group rules
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id

    - name: Add Controller internal ELB security group rules
      ec2_group:
        region: "{{ aws_region }}"
        name: "{{ ctrl_int_elb_sg_name }}"
        description: Security group for controller internal ELB devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            group_name: "{{ edge_sg_name }}"
          - proto: tcp
            from_port: 8080
            to_port: 8080
            group_name: "{{ sn_sg_name }}"
        rules_egress:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            group_name: "{{ ctrl_sg_name }}"
        purge_rules: true
        purge_rules_egress: true

    - name: Add Controller ELB security group rules
      ec2_group:
        region: "{{ aws_region }}"
        name: "{{ ctrl_elb_sg_name }}"
        description: Security group for Controller ELB devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 9443
            to_port: 9443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          #Monitoring
          - proto: tcp
            from_port: 8666
            to_port: 8666
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 9443
            to_port: 9443
            group_name: "{{ ctrl_sg_name }}"
          - proto: tcp
            from_port: 8443
            to_port: 8443
            group_name: "{{ ctrl_sg_name }}"
          #Monitoring
          - proto: tcp
            from_port: 8666
            to_port: 8666
            group_name: "{{ ctrl_sg_name }}"

        purge_rules: true
        purge_rules_egress: true