- name: Create Jump Server security group and add rules
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id

    - ec2_group:
        region: "{{ aws_region }}"
        name: "{{ jump_sg_name }}"
        description: Security group for Jump Server devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 172.16.0.0/16
          - proto: udp
            from_port: 53
            to_port: 53
            cidr_ip: 172.16.0.2/32
          - proto: tcp
            from_port: 53
            to_port: 53
            cidr_ip: 172.16.0.2/32
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        purge_rules: true
        purge_rules_egress: true

      register: jump_sg

    - name: Check Jump Server security group created
      ec2_resource_checker:
        type: security_group
        id: "{{ jump_sg.group_id }}"
        region: "{{ aws_region }}"
      register: jump_sg_checker

    - debug: msg="{{ jump_sg_checker }}"

    - set_fact:
        security_groups: "{{ security_groups }} + [{{ jump_sg }}]"
