- name: Add Redis security group rules
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id

    - ec2_group:
        region: "{{ aws_region }}"
        name: "{{ redis_sg_name }}"
        description: Security group for Redis devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_name: "{{ jump_sg_name }}"
          - proto: tcp
            from_port: 6379
            to_port: 6379
            group_name: "{{ ctrl_sg_name }}"
        rules_egress: []
        purge_rules: true
        purge_rules_egress: true
