
- name: Update service node security group rules
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id


    - name: Add Service Node SG Rules
      ec2_group:
        region: "{{ aws_region }}"
        name: "{{ sn_sg_name }}"
        description: Security group for Service Node devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_name: "{{ jump_sg_name }}"
          - proto: tcp
            from_port: 443
            to_port: 443
            group_name: "{{ sn_elb_sg_name }}"
          - proto: tcp
            from_port: 443
            to_port: 443
            group_name: "{{ edge_sg_name }}"
        rules_egress:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            group_name: "{{ ctrl_int_elb_sg_name }}"
          - proto: udp
            from_port: 53
            to_port: 53
            cidr_ip: 172.16.0.2/32
          - proto: tcp
            from_port: 53
            to_port: 53
            cidr_ip: 172.16.0.2/32
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        purge_rules: true
        purge_rules_egress: true

    - name: Add Service Node ELB SG Rules
      ec2_group:
        region: "{{ aws_region }}"
        name: "{{ sn_elb_sg_name }}"
        description: Security group for Service Node ELB devices
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: tcp
            from_port: 443
            to_port: 443
            group_name: "{{ sn_sg_name }}"
        purge_rules: true
        purge_rules_egress: true