- name: Update tags for VPC resources
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id

    - name: Update tags for VPC Network ACLS

    - name: Update tags for VPC DHCP Options

    - name: Update tags for VPC Route Tables

    - name: Update tags for VPC Internet Gateway


