- name: Create Route53 Health Checks
  hosts: localhost
  connection: local
  vars_files:
    - vars/external_vars.yml
  
  tasks:
    - include: gather_facts.yaml
      when: not vpc_id

    - name: Create Controller Route53 Health Check
      route53_health_check_ex:
        action: create_https
        threshold: 3
        request_interval: 10
        fqdn: "aws-{{ dns_prefix }}-api.c.{{ dns_suffix }}.{{ dns_suffix2 }}"
        port: 9443
        resource_path: "/Control/Ping"
      register: controller_health_check

    - name: Add tags for Controller Route53 Health Check
      route53_health_check_ex:
        action: tags
        health_check_id: "{{ controller_health_check.result.HealthCheck.Id }}"
        tags: {Name: "Controller-HealthCheck-{{ dns_prefix }}-{{ naming_suffix }}"}

    - debug: msg="{{ controller_health_check }}"

    #- name: Create ServiceNode Route53 Health Check
    #  route53_health_check:
    #    state: present
    #    fqdn: "aws-{{ dns_prefix }}.g.{{ dns_suffix }}.{{ dns_suffix2 }}"
    #    type: TCP
    #    request_interval: 10
    #    failure_threshold: 3
    #    port: 443
    #  register: sn_health_check
    - name: Create ServiceNode Route53 Health Check
      route53_health_check_ex:
        action: create_https
        threshold: 3
        request_interval: 10
        fqdn: "aws-{{ dns_prefix }}.g.{{ dns_suffix }}.{{ dns_suffix2 }}"
        port: 443
        resource_path: "/Control/Ping"
      register: sn_health_check


    - debug: msg="{{ sn_health_check }}"

    - name: Add tags for ServiceNode Route53 Health Check
      route53_health_check_ex:
        action: tags
        health_check_id: "{{ sn_health_check.result.HealthCheck.Id }}"
        tags: {Name: "ServiceNode-HealthCheck-{{ dns_prefix }}-{{ naming_suffix }}"}

    #- debug: msg="{{ sn_health_check }}"

    - name: Create Edge Route53 Health Check
      route53_health_check_ex:
        action: create_https
        threshold: 3
        request_interval: 10
        fqdn: "aws-{{ dns_prefix }}-rdvz.g.{{ dns_suffix }}.{{ dns_suffix2 }}"
        port: 443
        resource_path: "/Control/Ping"
      register: edge_health_check

    - name: Add tags for Edge Route53 Health Check
      route53_health_check_ex:
        action: tags
        health_check_id: "{{ edge_health_check.result.HealthCheck.Id }}"
        tags: {Name: "Edge-HealthCheck-{{ dns_prefix }}-{{ naming_suffix }}"}

    #- debug: msg="{{ edge_health_check }}"

    - name: Create Calculated Route53 Health Check
      route53_health_check_ex:
        threshold: 3
        action: create_calculated
        health_check_ids: ["{{ controller_health_check.result.HealthCheck.Id }}","{{ sn_health_check.result.HealthCheck.Id }}", "{{ edge_health_check.result.HealthCheck.Id }}"]
      register: calculated_health_check

    - name: Add tags for Calculated Route53 Health Check
      route53_health_check_ex:
        action: tags
        health_check_id: "{{ calculated_health_check.result.HealthCheck.Id }}"
        tags: {Name: "Calculated-HealthCheck-{{ dns_prefix }}-{{ naming_suffix }}"}


      